export default function useTestData(k) {
    // 侧边菜单
    const asideMenus = [{
            name: "dashboard",
            title: "后台面板",
            icon: "compass",
            children: [{
                name: "/",
                title: "主控台"
            }]
        }, {
            name: "goods",
            title: "商品管理",
            icon: "compass",
            children: [{
                name: "/goods/list",
                title: "商品管理"
            }, {
                name: "/category/list",
                title: "分类管理"
            }, {
                name: "/skus/list",
                title: "规格管理"
            }, {
                name: "/coupon/list",
                title: "优惠券管理"
            }]
        },
        {
            name: "user",
            icon: "setting",
            title: "用户管理",
            children: [{
                name: "/user/list",
                title: "用户管理"
            }, {
                name: "/level/list",
                title: "会员等级"
            }]
        },
        {
            name: "order",
            icon: "setting",
            title: "订单管理",
            children: [{
                name: "/order/list",
                title: "订单管理"
            }, {
                name: "/comment/list",
                title: "评价管理"
            }]
        },
        {
            name: "manager",
            icon: "setting",
            title: "管理员管理",
            children: [{
                name: "/manager/list",
                title: "管理员管理"
            }, {
                name: "/role/list",
                title: "角色管理"
            }, {
                name: "/access/list",
                title: "权限管理"
            }]
        },
        {
            name: "setting",
            icon: "setting",
            title: "系统设置",
            children: [{
                name: "/setting/base",
                title: "基础设置"
            }, {
                name: "/setting/buy",
                title: "支付设置"
            }, {
                name: "/setting/ship",
                title: "物流设置"
            }]
        },
        {
            name: "other",
            icon: "setting",
            title: "其他模块",
            children: [{
                name: "/image/list",
                title: "图库管理"
            }, {
                name: "/notice/list",
                title: "公告管理"
            }]
        },
    ]

    // 首页图表
    const indexChart = {
        hour: { "x": ["09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00", "01", "02", "03", "04", "05", "06", "07", "08"], "y": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] },
        week: { "x": ["04-06", "04-07", "04-08", "04-09", "04-10", "04-11", "04-12"], "y": [0, 0, 1, 0, 2, 7, 0] },
        month: { "x": ["03-14", "03-15", "03-16", "03-17", "03-18", "03-19", "03-20", "03-21", "03-22", "03-23", "03-24", "03-25", "03-26", "03-27", "03-28", "03-29", "03-30", "03-31", "04-01", "04-02", "04-03", "04-04", "04-05", "04-06", "04-07", "04-08", "04-09", "04-10", "04-11", "04-12"], "y": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 7, 0] }
    }

    // sku列表
    const skus = {
        "list": [{
                "id": 209,
                "name": "张威",
                "type": 2,
                "create_time": "2021-04-12 16:52:36",
                "update_time": "2021-06-10 19:46:03",
                "status": 1,
                "order": 22225,
                "default": "222222222222"
            },
            {
                "id": 208,
                "name": "嗡嗡嗡",
                "type": 0,
                "create_time": "2021-04-12 16:51:47",
                "update_time": "2021-06-08 17:04:24",
                "status": 1,
                "order": 999,
                "default": "000000"
            },
            {
                "id": 207,
                "name": "身高",
                "type": 2,
                "create_time": "1970-01-01 08:33:41",
                "update_time": "2021-03-31 22:11:11",
                "status": 1,
                "order": 100,
                "default": "170,185"
            },
            {
                "id": 167,
                "name": "今天好气啊111",
                "type": 2,
                "create_time": "2020-02-25 14:35:03",
                "update_time": "2021-04-12 08:10:41",
                "status": 1,
                "order": 90,
                "default": "为什么生气"
            },
            {
                "id": 203,
                "name": "11111",
                "type": 0,
                "create_time": "2020-12-07 08:37:30",
                "update_time": "2021-04-12 08:10:43",
                "status": 1,
                "order": 80,
                "default": "shengeml'd;as\nshdjkjskdjsal\ndsadsdsa"
            },
            {
                "id": 190,
                "name": "马冬梅",
                "type": 0,
                "create_time": "2020-12-03 18:18:59",
                "update_time": "2021-06-08 18:21:33",
                "status": 1,
                "order": 75,
                "default": "我是谁"
            },
            {
                "id": 192,
                "name": "555",
                "type": 1,
                "create_time": "2020-12-03 18:34:22",
                "update_time": "2020-12-12 16:24:16",
                "status": 1,
                "order": 70,
                "default": "少时诵诗书所所所所所所"
            },
            {
                "id": 186,
                "name": "我没有闪",
                "type": 1,
                "create_time": "2020-12-03 15:34:48",
                "update_time": "2020-12-12 16:24:12",
                "status": 1,
                "order": 66,
                "default": "我大意了"
            },
            {
                "id": 166,
                "name": "品牌",
                "type": 1,
                "create_time": "2020-02-25 11:18:45",
                "update_time": "2020-12-03 15:30:43",
                "status": 1,
                "order": 66,
                "default": "我大意了"
            },
            {
                "id": 189,
                "name": "7777",
                "type": 2,
                "create_time": "2020-12-03 18:11:35",
                "update_time": "2021-04-12 08:10:45",
                "status": 1,
                "order": 65,
                "default": "2222222"
            },
            {
                "id": 191,
                "name": "耗子尾汁",
                "type": 0,
                "create_time": "2020-12-03 18:19:41",
                "update_time": "2021-04-12 08:10:45",
                "status": 1,
                "order": 60,
                "default": "我大意了1111111"
            },
            {
                "id": 211,
                "name": "珠海",
                "type": 1,
                "create_time": "2021-05-06 12:34:29",
                "update_time": "2021-05-06 12:34:29",
                "status": 1,
                "order": 50,
                "default": "A,B,C,D,E"
            },
            {
                "id": 210,
                "name": "123",
                "type": 0,
                "create_time": "2021-04-13 13:36:36",
                "update_time": "2021-04-13 13:36:36",
                "status": 1,
                "order": 50,
                "default": "fasdf"
            },
            {
                "id": 206,
                "name": "身高",
                "type": 0,
                "create_time": "2021-03-21 21:20:54",
                "update_time": "2021-04-12 08:10:50",
                "status": 1,
                "order": 50,
                "default": "150,160,170"
            },
            {
                "id": 205,
                "name": "品牌",
                "type": 0,
                "create_time": "2021-03-21 21:15:35",
                "update_time": "2021-03-21 21:15:35",
                "status": 1,
                "order": 50,
                "default": " 品牌1,品牌2"
            },
            {
                "id": 204,
                "name": "1",
                "type": 1,
                "create_time": "2020-12-07 16:48:06",
                "update_time": "2020-12-07 16:48:06",
                "status": 0,
                "order": 50,
                "default": "qqq"
            },
            {
                "id": 197,
                "name": "1",
                "type": 0,
                "create_time": "2020-12-03 20:26:22",
                "update_time": "2020-12-03 20:26:22",
                "status": 1,
                "order": 50,
                "default": "1"
            },
            {
                "id": 193,
                "name": "今天",
                "type": 2,
                "create_time": "2020-12-03 18:36:16",
                "update_time": "2020-12-04 08:54:14",
                "status": 0,
                "order": 50,
                "default": "为什么"
            },
            {
                "id": 180,
                "name": "123",
                "type": 0,
                "create_time": "2020-12-02 11:11:52",
                "update_time": "2020-12-03 21:51:26",
                "status": 0,
                "order": 50,
                "default": "123"
            },
            {
                "id": 176,
                "name": "达娃1111",
                "type": 0,
                "create_time": "2020-12-02 09:36:05",
                "update_time": "2020-12-03 15:21:12",
                "status": 1,
                "order": 50,
                "default": "达娃"
            }
        ],
        "totalCount": 56
    }

    let distributions = {
        "count": 443,
        "list": [
            {
                "user_id": 12958,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "dd3f5eb5d63b",
                "avatar": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "phone": "136****6206",
                "add_time": 1651504568,
                "last_time": 1651504568,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "h5",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 1,
                "is_ever_level": 0,
                "overdue_time": 1652109372,
                "uniqid": "",
                "bar_code": "569749316",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12957,
                "real_name": "袁晓宾",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "一路向北",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/zfaUB2EXUNO6BcXIKSD3CzrficV7zFFbL9P3SKwd5AEHh2RiaTQCYOXP45CXdQTfU7ME0biaI3KOOibMklvoad2Iiaw/132",
                "phone": "188****3622",
                "add_time": 1651490925,
                "last_time": 1651490925,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 1,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "18839063622",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "101492834",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/zfaUB2EXUNO6BcXIKSD3CzrficV7zFFbL9P3SKwd5AEHh2RiaTQCYOXP45CXdQTfU7ME0biaI3KOOibMklvoad2Iiaw/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": "0.01",
                "order_count": 1,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12956,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "【正鲜森】㊣【荔枝酸芒果直发】",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLzOGE466kJzflkgIyJG91orGz4e7F7RYpuqIEYD1RXUZSTUB9xvY7ibsfVfJrM7lbQnXttjpNYG5Q/132",
                "phone": "186****5213",
                "add_time": 1651470051,
                "last_time": 1651470051,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "519740870",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTLzOGE466kJzflkgIyJG91orGz4e7F7RYpuqIEYD1RXUZSTUB9xvY7ibsfVfJrM7lbQnXttjpNYG5Q/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12955,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "赵盼盼（专注: 企业营销获客）",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/9KOlicydNpGV1DPImERHYLrJRsjq0BKUBVOLXPm522sCpDd6OsrN3dWhMqCib72mq6IJ8saEl7cVGkkq3ygDHZdg/132",
                "phone": "181****5664",
                "add_time": 1651454289,
                "last_time": 1651454289,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "491000551",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/9KOlicydNpGV1DPImERHYLrJRsjq0BKUBVOLXPm522sCpDd6OsrN3dWhMqCib72mq6IJ8saEl7cVGkkq3ygDHZdg/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12954,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "顾参谋",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eoXpiar6GkwWIg2WNhV95iaH0cic2HdeRYZGfjsHMYPtowrEwLRvgppVaVJxmMPyzlt00Ok6nmWCqDdg/132",
                "phone": "187****8613",
                "add_time": 1651422749,
                "last_time": 1651422749,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "100968481",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83eoXpiar6GkwWIg2WNhV95iaH0cic2HdeRYZGfjsHMYPtowrEwLRvgppVaVJxmMPyzlt00Ok6nmWCqDdg/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12953,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "π",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/waYiaicoCro4k6KAayxkCTZsmCHCcnb9Yg8UMdsUnicLtt1EyHZiboFfw8jJWwWKFFfTYssKro5ibjDaugoe3OnNAFA/132",
                "phone": "158****8891",
                "add_time": 1651415842,
                "last_time": 1651415842,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "515066476",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/waYiaicoCro4k6KAayxkCTZsmCHCcnb9Yg8UMdsUnicLtt1EyHZiboFfw8jJWwWKFFfTYssKro5ibjDaugoe3OnNAFA/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12952,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "Andy",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/glMH9jUOFSibU2bQVRRuicfB7EIbvCZYHBblpYKrZSIpPF06l2eNYZ4hxiaqD974rOZeiaHH10fM6wBSrBEFgRt8xA/132",
                "phone": "136****8836",
                "add_time": 1651415715,
                "last_time": 1651415715,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "511049024",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/glMH9jUOFSibU2bQVRRuicfB7EIbvCZYHBblpYKrZSIpPF06l2eNYZ4hxiaqD974rOZeiaHH10fM6wBSrBEFgRt8xA/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12951,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "鸿运",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epBZUdoPMcqJHEiae0MjLbUyI33RjuXE58E8v79aoW86RIEib5K9Pttc6icibeblvDvs3H18vK302RrqQ/132",
                "phone": "166****0909",
                "add_time": 1651405330,
                "last_time": 1651405337,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 1,
                "is_ever_level": 0,
                "overdue_time": 1652010189,
                "uniqid": "",
                "bar_code": "509854060",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/DYAIOgq83epBZUdoPMcqJHEiae0MjLbUyI33RjuXE58E8v79aoW86RIEib5K9Pttc6icibeblvDvs3H18vK302RrqQ/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12950,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "高原",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/UNxaU0OgwKogEo1IEzI8qNWzwlvUy7IySYpv7SbaK6RqJ8ADe10s85vyERke1SY6AZKELzHOaFyMPjicgpQtslw/132",
                "phone": "176****6248",
                "add_time": 1651395323,
                "last_time": 1651395323,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "981068166",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/UNxaU0OgwKogEo1IEzI8qNWzwlvUy7IySYpv7SbaK6RqJ8ADe10s85vyERke1SY6AZKELzHOaFyMPjicgpQtslw/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12949,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "",
                "avatar": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "phone": "151****6011",
                "add_time": 1651370843,
                "last_time": 1651370843,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 1,
                "is_ever_level": 0,
                "overdue_time": 1651975736,
                "uniqid": "",
                "bar_code": "985635126",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12948,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "db230a6c8a98",
                "avatar": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "phone": "155****9737",
                "add_time": 1651332122,
                "last_time": 1651332122,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "app",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "979806695",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12947,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "wr",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/aibMTHedczibwYH45OMOmqiaiaezKj882dia7XicHX59dJ96hq8gwoChjXIJc0nfERvIm6WwEc4yA8IAnYAMnImUouLQ/132",
                "phone": "136****9819",
                "add_time": 1651329089,
                "last_time": 1651329089,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "491024030",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/aibMTHedczibwYH45OMOmqiaiaezKj882dia7XicHX59dJ96hq8gwoChjXIJc0nfERvIm6WwEc4yA8IAnYAMnImUouLQ/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12946,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "清揚O_o",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/ibG2jJKUrkibYYR3lQ1R551UibP7nQ42dW9WBQ4tYnh3dt3jMvBP1xFnse4k6sAGZiaf4kT8Ful0NO9eQTTeFvQXag/132",
                "phone": "130****4465",
                "add_time": 1651328829,
                "last_time": 1651328829,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "100584327",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/ibG2jJKUrkibYYR3lQ1R551UibP7nQ42dW9WBQ4tYnh3dt3jMvBP1xFnse4k6sAGZiaf4kT8Ful0NO9eQTTeFvQXag/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12945,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "c3f5f66ecd98",
                "avatar": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "phone": "186****5262",
                "add_time": 1651322348,
                "last_time": 1651322348,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "h5",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "991005089",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "http://tangzhe123-com.oss-cn-shenzhen.aliyuncs.com/public/5f50505928e60.jpg",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            },
            {
                "user_id": 12944,
                "real_name": "",
                "birthday": 0,
                "card_id": "",
                "mark": "",
                "partner_id": 0,
                "group_id": 0,
                "nickname": "喂马劈柴下一句",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKjJBcGldicK7dwBQtHaic8BmT6oYf8iatYzGQMUs4LWm76IBh3lmrzaAoaVOtL6QEViafzicqH1DKJmKg/132",
                "phone": "151****5155",
                "add_time": 1651321212,
                "last_time": 1651321212,
                "now_money": "0.00",
                "brokerage_price": "0.00",
                "integral": 0,
                "exp": null,
                "sign_num": 0,
                "status": 1,
                "level": 0,
                "agent_level": 0,
                "spread_open": 1,
                "spread_user_id": 0,
                "spread_time": 0,
                "spread_lottery": 1,
                "user_type": "routine",
                "is_promoter": 1,
                "pay_count": 0,
                "spread_count": 0,
                "addres": "",
                "adminid": 0,
                "login_type": "",
                "record_phone": "0",
                "is_money_level": 0,
                "is_ever_level": 0,
                "overdue_time": 0,
                "uniqid": "",
                "bar_code": "991016232",
                "rand_code": 0,
                "sex": 0,
                "provincials": "",
                "province": 0,
                "city": 0,
                "area": 0,
                "street": 0,
                "brokerage": [],
                "agentLevel": null,
                "headimgurl": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTKjJBcGldicK7dwBQtHaic8BmT6oYf8iatYzGQMUs4LWm76IBh3lmrzaAoaVOtL6QEViafzicqH1DKJmKg/132",
                "extract_count_price": 0,
                "extract_count_num": 0,
                "spread_name": "",
                "order_price": 0,
                "order_count": 0,
                "broken_commission": 0,
                "brokerage_money": 0,
                "new_money": "0.00"
            }
        ]
    }




    const distribution_orders = {
        "list": [
            {
                "id": 2523,
                "type": 0,
                "pid": 0,
                "order_id": "wx230384427769790464",
                "trade_no": "",
                "uid": 37,
                "real_name": "Handson",
                "user_phone": "136****6802",
                "user_address": "    ",
                "user_location": "",
                "cart_id": [
                    "4036",
                    "4035"
                ],
                "activity_id": 0,
                "activity_append": "",
                "freight_price": "0.00",
                "total_num": 2,
                "total_price": "798.00",
                "total_postage": "0.00",
                "pay_price": "798.00",
                "pay_postage": "0.00",
                "deduction_price": "0.00",
                "coupon_id": 0,
                "coupon_price": "0.00",
                "paid": 1,
                "pay_time": 1646214327,
                "pay_type": "cash",
                "add_time": 1646214327,
                "status": 2,
                "refund_status": 0,
                "refund_type": 0,
                "refund_express": "",
                "refund_reason_wap_img": null,
                "refund_reason_wap_explain": null,
                "refund_reason_time": null,
                "refund_reason_wap": null,
                "refund_reason": null,
                "refund_price": "0.00",
                "delivery_name": null,
                "delivery_code": "",
                "delivery_type": "cashier",
                "delivery_id": null,
                "fictitious_content": "",
                "delivery_uid": 0,
                "gain_integral": "500.00",
                "use_integral": "0.00",
                "back_integral": null,
                "spread_uid": 37,
                "spread_two_uid": 0,
                "one_brokerage": "79.80",
                "two_brokerage": "0.00",
                "mark": "",
                "is_del": 0,
                "unique": "4fe5872018f8baac3f0065960f84e665",
                "remark": null,
                "mer_id": 0,
                "is_mer_check": 0,
                "pink_id": 0,
                "cost": "199.00",
                "verify_code": "",
                "store_id": 10,
                "staff_id": 4,
                "shipping_type": 4,
                "clerk_id": 0,
                "is_channel": 2,
                "is_remind": 0,
                "is_system_del": 0,
                "channel_type": "wechat",
                "province": "",
                "express_dump": "",
                "product_type": 0,
                "virtual_info": "",
                "custom_form": [],
                "user_info": "Handson|136****6802|Handson",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJU3cUjqq2R17FBm4gibxevbJCv9y9gmnH93cmictRibmib04YBCP4Slgiarx2YEOdnlsvndWMeiaEoCw2Q/132",
                "brokerage_price": "79.80",
                "_pay_time": "2022-03-02 17:45:27",
                "_add_time": "2022-03-02 17:45:27",
                "take_time": "2022-03-02 17:45:28"
            },
            {
                "id": 2321,
                "type": 0,
                "pid": 0,
                "order_id": "wx214813225668050944",
                "trade_no": "",
                "uid": 37,
                "real_name": "Handson",
                "user_phone": "136****6802",
                "user_address": "    ",
                "user_location": "",
                "cart_id": [
                    "3566",
                    "3563"
                ],
                "activity_id": 0,
                "activity_append": "",
                "freight_price": "0.00",
                "total_num": 2,
                "total_price": "698.00",
                "total_postage": "0.00",
                "pay_price": "698.00",
                "pay_postage": "0.00",
                "deduction_price": "0.00",
                "coupon_id": 0,
                "coupon_price": "0.00",
                "paid": 1,
                "pay_time": 1642501864,
                "pay_type": "cash",
                "add_time": 1642501864,
                "status": 2,
                "refund_status": 0,
                "refund_type": 0,
                "refund_express": "",
                "refund_reason_wap_img": null,
                "refund_reason_wap_explain": null,
                "refund_reason_time": null,
                "refund_reason_wap": null,
                "refund_reason": null,
                "refund_price": "0.00",
                "delivery_name": null,
                "delivery_code": "",
                "delivery_type": "cashier",
                "delivery_id": null,
                "fictitious_content": "",
                "delivery_uid": 0,
                "gain_integral": "500.00",
                "use_integral": "0.00",
                "back_integral": null,
                "spread_uid": 37,
                "spread_two_uid": 0,
                "one_brokerage": "69.80",
                "two_brokerage": "0.00",
                "mark": "",
                "is_del": 0,
                "unique": "7ff0cced3fea8b4510bffcdd6a37928a",
                "remark": null,
                "mer_id": 0,
                "is_mer_check": 0,
                "pink_id": 0,
                "cost": "189.00",
                "verify_code": "",
                "store_id": 10,
                "staff_id": 4,
                "shipping_type": 4,
                "clerk_id": 0,
                "is_channel": 2,
                "is_remind": 0,
                "is_system_del": 0,
                "channel_type": "wechat",
                "province": "",
                "express_dump": "",
                "product_type": 0,
                "virtual_info": "",
                "custom_form": [],
                "user_info": "Handson|136****6802|Handson",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJU3cUjqq2R17FBm4gibxevbJCv9y9gmnH93cmictRibmib04YBCP4Slgiarx2YEOdnlsvndWMeiaEoCw2Q/132",
                "brokerage_price": "69.80",
                "_pay_time": "2022-01-18 18:31:04",
                "_add_time": "2022-01-18 18:31:04",
                "take_time": "2022-01-18 18:31:06"
            },
            {
                "id": 2298,
                "type": 0,
                "pid": 0,
                "order_id": "wx213833820309291008",
                "trade_no": "",
                "uid": 37,
                "real_name": "Handson",
                "user_phone": "136****6802",
                "user_address": "    ",
                "user_location": "",
                "cart_id": [
                    "3546",
                    "3545"
                ],
                "activity_id": 0,
                "activity_append": "",
                "freight_price": "0.00",
                "total_num": 2,
                "total_price": "998.00",
                "total_postage": "0.00",
                "pay_price": "998.00",
                "pay_postage": "0.00",
                "deduction_price": "0.00",
                "coupon_id": 0,
                "coupon_price": "0.00",
                "paid": 1,
                "pay_time": 1642268355,
                "pay_type": "cash",
                "add_time": 1642268355,
                "status": 2,
                "refund_status": 0,
                "refund_type": 0,
                "refund_express": "",
                "refund_reason_wap_img": null,
                "refund_reason_wap_explain": null,
                "refund_reason_time": null,
                "refund_reason_wap": null,
                "refund_reason": null,
                "refund_price": "0.00",
                "delivery_name": null,
                "delivery_code": "",
                "delivery_type": "cashier",
                "delivery_id": null,
                "fictitious_content": "",
                "delivery_uid": 0,
                "gain_integral": "500.00",
                "use_integral": "0.00",
                "back_integral": null,
                "spread_uid": 37,
                "spread_two_uid": 0,
                "one_brokerage": "99.80",
                "two_brokerage": "0.00",
                "mark": "",
                "is_del": 0,
                "unique": "cd8b0236cc7119633cb86098a5fcbdbc",
                "remark": null,
                "mer_id": 0,
                "is_mer_check": 0,
                "pink_id": 0,
                "cost": "399.00",
                "verify_code": "",
                "store_id": 10,
                "staff_id": 4,
                "shipping_type": 4,
                "clerk_id": 0,
                "is_channel": 2,
                "is_remind": 0,
                "is_system_del": 0,
                "channel_type": "wechat",
                "province": "",
                "express_dump": "",
                "product_type": 0,
                "virtual_info": "",
                "custom_form": [],
                "user_info": "Handson|136****6802|Handson",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJU3cUjqq2R17FBm4gibxevbJCv9y9gmnH93cmictRibmib04YBCP4Slgiarx2YEOdnlsvndWMeiaEoCw2Q/132",
                "brokerage_price": "99.80",
                "_pay_time": "2022-01-16 01:39:15",
                "_add_time": "2022-01-16 01:39:15",
                "take_time": "2022-01-16 01:39:15"
            },
            {
                "id": 1553,
                "type": 0,
                "pid": 0,
                "order_id": "wx187561295862562816",
                "trade_no": "",
                "uid": 37,
                "real_name": "哈哈",
                "user_phone": "13602516802",
                "user_address": "    ",
                "user_location": " ",
                "cart_id": [
                    "37187561147027685376"
                ],
                "activity_id": 0,
                "activity_append": "",
                "freight_price": "0.00",
                "total_num": 1,
                "total_price": "0.01",
                "total_postage": "0.00",
                "pay_price": "0.01",
                "pay_postage": "0.00",
                "deduction_price": "0.00",
                "coupon_id": 0,
                "coupon_price": "0.00",
                "paid": 1,
                "pay_time": 1636004497,
                "pay_type": "yue",
                "add_time": 1636004497,
                "status": 2,
                "refund_status": 0,
                "refund_type": 0,
                "refund_express": "",
                "refund_reason_wap_img": null,
                "refund_reason_wap_explain": null,
                "refund_reason_time": null,
                "refund_reason_wap": null,
                "refund_reason": null,
                "refund_price": "0.00",
                "delivery_name": null,
                "delivery_code": "",
                "delivery_type": null,
                "delivery_id": null,
                "fictitious_content": "",
                "delivery_uid": 0,
                "gain_integral": "1.00",
                "use_integral": "0.00",
                "back_integral": null,
                "spread_uid": 37,
                "spread_two_uid": 0,
                "one_brokerage": "0.00",
                "two_brokerage": "0.00",
                "mark": "",
                "is_del": 0,
                "unique": "d9ae94d89e0598edab2e82692c2f8681",
                "remark": null,
                "mer_id": 0,
                "is_mer_check": 0,
                "pink_id": 0,
                "cost": "49.00",
                "verify_code": "163618610265",
                "store_id": 12,
                "staff_id": 10,
                "shipping_type": 2,
                "clerk_id": 0,
                "is_channel": 1,
                "is_remind": 0,
                "is_system_del": 0,
                "channel_type": "wechat",
                "province": "陕西",
                "express_dump": "",
                "product_type": 0,
                "virtual_info": "",
                "custom_form": [],
                "user_info": "Handson|136****6802|Handson",
                "avatar": "https://thirdwx.qlogo.cn/mmopen/vi_32/Q0j4TwGTfTJU3cUjqq2R17FBm4gibxevbJCv9y9gmnH93cmictRibmib04YBCP4Slgiarx2YEOdnlsvndWMeiaEoCw2Q/132",
                "brokerage_price": "0.00",
                "_pay_time": "2021-11-04 13:41:37",
                "_add_time": "2021-11-04 13:41:37",
                "take_time": "暂无"
            }
        ],
        "count": 4
    }

    let o = {
        asideMenus,
        indexChart,
        distributions,
        distribution_orders,
        skus
    }

    return o[k] || []
}